FROM huggingface/transformers-pytorch-cpu

RUN pip3 install --upgrade pip
RUN pip3 install setuptools_rust

COPY requirements.txt /
RUN pip3 install -r /requirements.txt

COPY . /app
WORKDIR /app

ENTRYPOINT ["./run_bot.sh"]
